### ISSUE TITLE
Unable to use ansible galaxy to download role

### ISSUE THREAD

**Issue by keitalbame** [jtyr/ansible-nginx#1]
It is not possible to download the role using ansible galaxy.

```
$ ansible-galaxy install jtyr.nginx
- downloading role 'nginx', owned by jtyr
- downloading role from https://github.com/jtyr/ansible-nginx/archive/master.tar.gz
 [WARNING]: - jtyr.nginx was NOT installed successfully: this role does not appear to have a meta/main.yml file.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

I suspect the issue is that `meta/main.yml` is using `meta/main.yaml` instead.

**Comment by jtyr** [comment]
Correct. This has been fixed (https://github.com/ansible/ansible/pull/46505) and should be part of Ansible v2.8. Please make sure you run this version or newer.

**Comment by keitalbame** [comment]
I was using using ansible(2.5) from Ubuntu 18.04 repos.
Installed from pip and now is working.
Thanks
